[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = false
skip-lint = false

[programs.localnet]
energy_token = "B9LnEVqqz8ZVgZ4zELtxXYozXQbm1eo1KD2x3rAMMcTH"
governance = "4H7HQ3aRdXkGhAxvAyLKY37c8BS1Do8zjLdR5mRAcVn5"
oracle = "4zfVZ9KkgxvYbkdGwN46b7XW7PL9wFahUwGaJp18dBX9"
registry = "C5HLtbZHgwVU2oMirgd9f62Zeig7hZFKyJuB9AqVcsn6"
trading = "5e8URdeycFDUZL33HYhhEMY928BJCTPn4xAnhJhKb3SA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
init-governance = "npx ts-node scripts/init-governance.ts"
init-market = "npx ts-node scripts/init-market.ts"
init-oracle = "npx ts-node scripts/init-oracle.ts"
update-gateway = "npx ts-node scripts/update-gateway.ts"
init-poa = "npx ts-node scripts/init-poa.ts"
init-registry = "npx tsx scripts/init-registry.ts"
init-sharding = "npx ts-node scripts/initialize-sharding.ts"
init-shards = "npx tsx scripts/init-shards.ts"
init-zone-market = "npx ts-node scripts/init-zone-market.ts"
mint-tokens = "npx ts-node scripts/mint-tokens.ts"
setup-alts = "npx ts-node scripts/setup-alts.ts"
test-oracle = "anchor test tests/oracle.ts"
test-registry = "anchor test tests/registry_sharding.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
