[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = false
skip-lint = false

[programs.localnet]
energy_token = "B9LnEVqqz8ZVgZ4zELtxXYozXQbm1eo1KD2x3rAMMcTH"
registry = "C5HLtbZHgwVU2oMirgd9f62Zeig7hZFKyJuB9AqVcsn6"
trading = "5e8URdeycFDUZL33HYhhEMY928BJCTPn4xAnhJhKb3SA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
init-registry = "npx tsx scripts/init-registry.ts"
init-shards = "npx tsx scripts/init-shards.ts"
init-energy = "npx tsx scripts/init-token.ts"
mint-tokens = "npx ts-node scripts/mint-tokens.ts"
test-registry = "anchor test tests/registry_sharding.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
